#Configuration file for Google Cloud Builds

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '.',
           '-t', 'eu.gcr.io/$PROJECT_ID/website-versioning-crawler:$TAG_NAME',
           '-t', 'eu.gcr.io/$PROJECT_ID/website-versioning-crawler:$SHORT_SHA',
           '-t', 'eu.gcr.io/$PROJECT_ID/website-versioning-crawler:latest']

images:
  - 'eu.gcr.io/$PROJECT_ID/website-versioning-crawler:$TAG_NAME'
  - 'eu.gcr.io/$PROJECT_ID/website-versioning-crawler:$SHORT_SHA'
  - 'eu.gcr.io/$PROJECT_ID/website-versioning-crawler:latest'

options:
  machineType: 'N1_HIGHCPU_8'